version: '3.5'

services:
  app-farm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3013:3013'
    environment:
      - API_PORT=3013
      - API_VERSION=0.1.0-beta
      - MONGO_URL=mongodb://app-db:27017/app
      - MONGO_USER=admin
      - MONGO_PWD=admin
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.farmaciamila.com.br"

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

